/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-02-10 06:55:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ajax.news;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(8);
    _jspx_dependants.put("/ajax/news/bottom.jsp", Long.valueOf(1675995262470L));
    _jspx_dependants.put("/ajax/news/google.jsp", Long.valueOf(1675996852221L));
    _jspx_dependants.put("/ajax/news/info.jsp", Long.valueOf(1675996750563L));
    _jspx_dependants.put("/ajax/news/main.jsp", Long.valueOf(1676012110010L));
    _jspx_dependants.put("/ajax/news/login.jsp", Long.valueOf(1675996807214L));
    _jspx_dependants.put("/ajax/news/menu.jsp", Long.valueOf(1675995963464L));
    _jspx_dependants.put("/ajax/news/top.jsp", Long.valueOf(1675995262478L));
    _jspx_dependants.put("/ajax/news/board.jsp", Long.valueOf(1675997085103L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String menu = request.getParameter("menu"); // info or login or board or google

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\" />\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js\"></script>\r\n");
      out.write("<title>패턴1</title>\r\n");
      out.write("<style>\r\n");
      out.write("a {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script defer type = \"text/javascript\">\r\n");
      out.write("	const autoReload = () => {\r\n");
      out.write("  		console.log(\"autoReload 호출\")\r\n");
      out.write("  		 $.ajax({\r\n");
      out.write("  	          type: \"GET\", \r\n");
      out.write("  	          url: \"newsList.jsp\", //요청하고 있는 url페이지\r\n");
      out.write("  	          success: function (data) { //성공했을 때 \r\n");
      out.write("  	            $(\"#d_news\").html(data);\r\n");
      out.write("  	          },\r\n");
      out.write("  	          error:function(request, status, error){\r\n");
      out.write("  	        	  console.log(\"error\")\r\n");
      out.write("  	        	  console.log(\"error\" + request.status)\r\n");
      out.write("  	        	  console.log(\"error\" + request.responseText) //에러메시지 가져오는 명령어\r\n");
      out.write("  	          }\r\n");
      out.write("  	        });\r\n");
      out.write("  	}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <script type = \"text/javascript\">\r\n");
      out.write("  	$(document).ready(()=>{\r\n");
      out.write("  		//실행문이 오는 자리\r\n");
      out.write("  		start = () =>{\r\n");
      out.write("  			setInterval(autoReload, 2000); //autoReload는 함수이다. 일급함수 //2초지연발생\r\n");
      out.write("  		}\r\n");
      out.write("  		//function start(){}\r\n");
      out.write("  		start(); //호출 \r\n");
      out.write("  	})//end of ready - DOM을 다 읽었으면\r\n");
      out.write("  </script>\r\n");
      out.write("  \r\n");
      out.write("	<!-- 태그는 중첩해서 사용 가능함 -->\r\n");
      out.write("	<!-- 크기는 %로 주는 것이 좋다 가변적이니까 -->\r\n");
      out.write("	<table border=\"1\" align=\"center\" width=\"1000px\">\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td width=\"100%\" height=\"50px\">\r\n");
      out.write("				<!--====================top 시작====================-->\r\n");
      out.write("				");
      out.write("\r\n");
      out.write("          <table border=\"1\" width=\"100%\" height=\"100%\" bordercolor=\"green\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td>top 영역</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </table>");
      out.write("<!-- include : jsp에서 제공하는,, 페이지 변환?작업을 할 수 있는 예약어같은가 -->\r\n");
      out.write("				<!--====================top 끝====================-->\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>\r\n");
      out.write("				<!--====================body 시작====================-->\r\n");
      out.write("				<table>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<!--====================메뉴 시작====================-->\r\n");
      out.write("						<td width=\"200px\" height=\"400px\">\r\n");
      out.write("							");
      out.write("\r\n");
      out.write("<table border=\"1\" bordercolor=\"blue\" width=\"100%\" height=\"100%\">\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td valign = \"top\"> <!-- 위에 달라붙게하는 -->\r\n");
      out.write("                      <table>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                          <td><a href=\"./index.jsp?menu=info\" >소개</a></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                          <td><a href=\"./index.jsp?menu=login\">로그인</a></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                          <td><a href=\"./index.jsp?menu=board\" >게시판</a></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                          <td><a href=\"./index.jsp?menu=google\">구글</a></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                      </table>\r\n");
      out.write("                    </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                </table>");
      out.write("\r\n");
      out.write("						</td>\r\n");
      out.write("						<!--====================메뉴 끝====================-->\r\n");
      out.write("						<!--====================메인 시작====================-->\r\n");
      out.write("						<td width=\"800px\" height=\"400px\">\r\n");
//스크립틀릿
							if(menu == null){			

      out.write("\r\n");
      out.write("								");
      out.write("\r\n");
      out.write("<table border=\"1\" bordercolor=\"gray\" width=\"100%\" height=\"100%\">\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td><div id = \"d_news\"></div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                </table>");
      out.write('\r');
      out.write('\n');

							} else if("info".equals(menu)) { // 앞이 상수 뒤에 들어오는게 변수여야 nullPointerException 방어 가능

      out.write("\r\n");
      out.write("								");
      out.write("\r\n");
      out.write("          <table border=\"1\" width=\"100%\" height=\"100%\"  style = \"background-color:green\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td>info 영역</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </table>");
      out.write('\r');
      out.write('\n');

							} else if("login".equals(menu)) {

      out.write("								\r\n");
      out.write("								");
      out.write("\r\n");
      out.write("          <table border=\"1\" width=\"100%\" height=\"100%\"  style = \"background-color:yellow\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td>login 영역</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </table>");
      out.write('\r');
      out.write('\n');

							} else if("board".equals(menu)) {

      out.write("\r\n");
      out.write("								");
      out.write("\r\n");
      out.write("          <table border=\"1\" width=\"100%\" height=\"100%\"  style = \"background-color:blue\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td>board 영역</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </table>");
      out.write('\r');
      out.write('\n');

							} else if("google".equals(menu)) {

      out.write("\r\n");
      out.write("								");
      out.write("\r\n");
      out.write("          <table border=\"1\" width=\"100%\" height=\"100%\"  style = \"background-color:red\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td>google 영역</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </table>");
      out.write('\r');
      out.write('\n');

							}

      out.write("\r\n");
      out.write("						</td>\r\n");
      out.write("						<!--====================메인 끝====================-->\r\n");
      out.write("					</tr>\r\n");
      out.write("				</table> <!--====================body 끝====================-->\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td width=\"1000px\" height=\"30px\">\r\n");
      out.write("				<!--====================bottom 시작====================-->\r\n");
      out.write("				");
      out.write("\r\n");
      out.write("         <table border=\"1\" width=\"100%\" height=\"100%\" bordercolor=\"red\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td>bottom 영역</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </table>");
      out.write("\r\n");
      out.write("				<!--====================bottom 끝====================-->\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
